using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SpinnakerNET;

namespace UndergradResearchBiomedImaging.Flir.Settings {
	public class TestPatternSetting : FlirSetting {

		public override string Description { get; protected set; } = "Selects the type of test pattern that is generated by the device as image source.";
		public override string Command { get; protected set; } = "TestPattern";
		public override string DisplayName { get; protected set; } = "Test Pattern";

		public TestPatternSetting(FlirCamera camera) : base(camera) {
		}

		public bool TryWriteValue(TestPatternEnums pattern) {
			return trySetNodeValue(pattern.ToString());
		}

	}
}
